name: com.example.app_movil_proyecto_final
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.4.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #google fonts  
  google_fonts: ^5.1.0
  #percent indicator
  percent_indicator: ^4.2.3
  #carousel slider
  carousel_slider: ^4.2.1
  #smooth page indicator
  smooth_page_indicator: ^1.1.0

  #Authenticacion con Google - Firebase

  #firebase core
  firebase_core: ^2.14.0
  #firebase core_web
  firebase_core_web: ^2.6.0

  #firebase auth
  firebase_auth: ^4.6.3

  firebase_storage: ^11.6.0

  #cloud firestore
  cloud_firestore: ^4.8.1
  #google firestore
  google_sign_in: ^6.1.4
  #sign button
  sign_button: ^2.0.4

  #phone country
  intl_phone_field: ^3.2.0

  #shared preferences
  shared_preferences: ^2.2.0

  #provider
  provider: ^6.0.5

  #flutter iconly
  flutter_iconly: ^1.0.2

  #card swiper
  card_swiper: ^3.0.1

  #fancy shimmer image
  fancy_shimmer_image: ^2.0.3

  #flutter staggered grid view
  flutter_staggered_grid_view: ^0.6.1

  #flutter_spinkit
  flutter_spinkit: ^5.2.0

  #intl_phone_number_input
  intl_phone_number_input: ^0.7.3+1

  #path_provider
  path_provider: ^2.1.0

  #http
  http: ^1.1.0

  #fluttertoast
  fluttertoast: ^8.0.7

  #dio
  dio: ^5.3.2

  #flutter_downloader
  flutter_downloader: ^1.11.6

  #permission_handler
  permission_handler: ^10.4.3

  flutter_local_notifications: ^16.3.0

  #flutter_pdfview
  flutter_pdfview: ^1.3.1

  #flutter_rating_bar
  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.2

  google_maps_flutter: ^2.5.0

  location: ^5.0.3

  url_launcher: ^6.2.2

  flutter_custom_tabs: ^1.2.1

  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/mangas/shonen/
    - images/mangas/romance/
    - images/mangas/gore/
    - iconos/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
